# Generated by Django 4.1.7 on 2023-03-13 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_hospital_doctor_university_gpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('maxPatients', models.IntegerField()),
                ('nrRooms', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.clinic'),
        ),
    ]
