# Generated by Django 4.1.7 on 2023-03-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_clinic_alter_doctor_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='Missing phone', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('citizenship', models.CharField(max_length=25)),
            ],
        ),
    ]
