# Generated by Django 4.1.7 on 2023-03-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='maxPatients',
            new_name='beds',
        ),
    ]
