# Generated by Django 4.1.7 on 2023-03-20 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctor_hospital_bloodbag_doctor_donors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbag',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
