# Generated by Django 4.1.7 on 2023-03-20 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_bloodbag_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='donors',
            new_name='collected_donations',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='doctors',
            new_name='donations',
        ),
        migrations.AlterField(
            model_name='bloodbag',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
