# Generated by Django 4.1.7 on 2023-03-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_rename_donors_doctor_collected_donations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='university_gpa',
            field=models.FloatField(default=0),
        ),
    ]
