# Generated by Django 4.1.7 on 2023-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_bloodbag_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='donors',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='doctors',
        ),
        migrations.AlterField(
            model_name='doctorsdonors',
            name='donor',
            field=models.IntegerField(),
        ),
    ]
