# Generated by Django 4.1.7 on 2023-04-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_remove_doctor_donors_remove_donor_doctors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='description',
            field=models.CharField(default='Missing name', max_length=500),
        ),
    ]
