# Generated by Django 4.1.7 on 2023-04-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_donor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='donors',
            field=models.ManyToManyField(related_name='donors_set', through='doctors.DoctorsDonors', to='doctors.donor'),
        ),
        migrations.AddField(
            model_name='donor',
            name='doctors',
            field=models.ManyToManyField(through='doctors.DoctorsDonors', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorsdonors',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.donor'),
        ),
    ]
